[package]
name = "freedesktop-rs"
version = "0.1.0"
edition = "2024"

[features]
trash = ["dep:time"]

[dependencies]
nom = "8.0.0"
time = { version = "0.3.41", features = ["std", "formatting", "parsing", "macros" ], optional = true }
